export interface Recipe {
  id: string;
  name: string;
  category: 'Café da Manhã' | 'Lanche' | 'Almoço' | 'Jantar' | 'Sobremesa' | 'Bebida';
  type: 'Doce' | 'Salgado';
  ingredients: string[];
  calories: number;
  prepTime: string;
  difficulty: 'Fácil' | 'Médio' | 'Difícil';
  instructions: string[];
  protein: number;
  carbs: number;
  fats: number;
  tags: string[];
}

export const recipesDatabase: Recipe[] = [
  // ALMOÇO E JANTAR - 30 RECEITAS
  {
    id: 'almoco1',
    name: 'Frango grelhado com legumes',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      '1 peito de frango',
      '1 xícara de legumes (brócolis, cenoura, abobrinha)',
      'Sal, azeite e pimenta a gosto',
    ],
    calories: 320,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 35,
    carbs: 15,
    fats: 10,
    tags: ['Proteico', 'Baixo Carboidrato', 'Grelhado'],
    instructions: [
      'Tempere o frango com sal e pimenta.',
      'Coloque-o em uma frigideira com fio de azeite e grelhe dos dois lados até dourar.',
      'Em outra panela, refogue rapidamente os legumes com azeite e sal.',
      'Sirva tudo junto.',
    ],
  },
  {
    id: 'almoco2',
    name: 'Salada completa com frango desfiado',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      '1 prato de folhas verdes',
      '½ peito de frango desfiado',
      '1 tomate picado',
      '½ cenoura ralada',
      'Azeite e limão',
    ],
    calories: 280,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 28,
    carbs: 12,
    fats: 8,
    tags: ['Proteico', 'Leve', 'Salada'],
    instructions: [
      'Misture as folhas, tomate e cenoura.',
      'Acrescente o frango desfiado.',
      'Tempere com limão, azeite e sal.',
    ],
  },
  {
    id: 'almoco3',
    name: 'Tilápia assada com limão e ervas',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      '1 filé de tilápia',
      'Suco de 1 limão',
      'Sal, azeite e ervas (alecrim, orégano)',
    ],
    calories: 220,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 30,
    carbs: 2,
    fats: 8,
    tags: ['Proteico', 'Assado', 'Peixe'],
    instructions: [
      'Tempere a tilápia com limão, sal e ervas.',
      'Coloque em uma forma com fio de azeite.',
      'Asse por 20 minutos a 200°C.',
    ],
  },
  {
    id: 'almoco4',
    name: 'Estrogonoff fit com iogurte',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      '200 g de frango picado',
      '2 colheres (sopa) de iogurte natural',
      '½ cebola picada',
      '2 colheres (sopa) de molho de tomate',
    ],
    calories: 340,
    prepTime: '20 min',
    difficulty: 'Médio',
    protein: 32,
    carbs: 18,
    fats: 12,
    tags: ['Proteico', 'Cremoso', 'Fit'],
    instructions: [
      'Refogue a cebola e o frango.',
      'Junte o molho de tomate.',
      'Desligue o fogo e misture o iogurte.',
      'Mexa e sirva com arroz integral.',
    ],
  },
  {
    id: 'almoco5',
    name: 'Abóbora recheada com carne moída',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      '1 pedaço grande de abóbora',
      '150 g carne moída',
      'Temperos',
    ],
    calories: 380,
    prepTime: '35 min',
    difficulty: 'Médio',
    protein: 28,
    carbs: 25,
    fats: 15,
    tags: ['Proteico', 'Assado', 'Recheado'],
    instructions: [
      'Asse a abóbora 20 min até amolecer.',
      'Refogue carne moída com temperos.',
      'Recheie a abóbora e leve ao forno por mais 10 min.',
    ],
  },
  {
    id: 'almoco6',
    name: 'Arroz integral com frango e cenoura',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      '½ cebola',
      '¾ xícara de arroz integral',
      'Frango cozido',
      'Cenoura ralada',
      'Azeite',
    ],
    calories: 420,
    prepTime: '30 min',
    difficulty: 'Fácil',
    protein: 30,
    carbs: 48,
    fats: 10,
    tags: ['Completo', 'Proteico', 'Integral'],
    instructions: [
      'Refogue ½ cebola com azeite.',
      'Acrescente ¾ xícara de arroz integral e mexa.',
      'Adicione água e cozinhe.',
      'Misture frango cozido e cenoura ralada.',
    ],
  },
  {
    id: 'almoco7',
    name: 'Espaguete de abobrinha ao molho de tomate',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      '2 abobrinhas médias',
      'Molho de tomate caseiro',
      'Azeite',
      'Ervas frescas',
    ],
    calories: 180,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 6,
    carbs: 22,
    fats: 8,
    tags: ['Baixo Carboidrato', 'Vegetariano', 'Leve'],
    instructions: [
      'Passe a abobrinha no "espiralizador".',
      'Refogue rapidamente em azeite.',
      'Acrescente molho de tomate caseiro.',
      'Finalize com ervas.',
    ],
  },
  {
    id: 'almoco8',
    name: 'Carne moída magra com batata-doce',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      '150 g de carne magra',
      'Sal, alho e cebola',
      'Batata-doce cozida',
    ],
    calories: 400,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 32,
    carbs: 35,
    fats: 12,
    tags: ['Proteico', 'Completo', 'Energético'],
    instructions: [
      'Refogue 150 g de carne magra.',
      'Tempere com sal, alho e cebola.',
      'Sirva com batata-doce cozida.',
    ],
  },
  {
    id: 'almoco9',
    name: 'Risoto fit de frango',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Cebola',
      'Arroz arbóreo',
      'Caldo quente',
      'Frango desfiado',
      'Iogurte natural',
    ],
    calories: 380,
    prepTime: '35 min',
    difficulty: 'Médio',
    protein: 28,
    carbs: 45,
    fats: 8,
    tags: ['Cremoso', 'Proteico', 'Italiano'],
    instructions: [
      'Refogue cebola e arroz arbóreo.',
      'Vá colocando caldo quente aos poucos.',
      'Quando estiver quase pronto, adicione frango desfiado.',
      'Finalize com um pouco de iogurte.',
    ],
  },
  {
    id: 'almoco10',
    name: 'Caçarola low carb de brócolis',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Brócolis cozido',
      '2 ovos',
      'Queijo cottage',
    ],
    calories: 240,
    prepTime: '30 min',
    difficulty: 'Fácil',
    protein: 22,
    carbs: 10,
    fats: 12,
    tags: ['Baixo Carboidrato', 'Proteico', 'Assado'],
    instructions: [
      'Misture brócolis cozido, 2 ovos e queijo cottage.',
      'Coloque em forma.',
      'Asse por 20–25 min.',
    ],
  },
  {
    id: 'almoco11',
    name: 'Hambúrguer caseiro magro',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      '150 g carne moída',
      'Sal e ervas',
      'Salada',
    ],
    calories: 280,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 30,
    carbs: 5,
    fats: 14,
    tags: ['Proteico', 'Grelhado', 'Rápido'],
    instructions: [
      'Modele 150 g carne moída com sal e ervas.',
      'Grelhe dos dois lados.',
      'Sirva com salada.',
    ],
  },
  {
    id: 'almoco12',
    name: 'Torta de frango sem farinha',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      'Frango desfiado',
      '2 ovos',
      'Queijo',
    ],
    calories: 320,
    prepTime: '30 min',
    difficulty: 'Fácil',
    protein: 35,
    carbs: 8,
    fats: 16,
    tags: ['Sem Glúten', 'Proteico', 'Assado'],
    instructions: [
      'Misture frango desfiado, 2 ovos e queijo.',
      'Coloque em forma pequena.',
      'Asse 25 min.',
    ],
  },
  {
    id: 'almoco13',
    name: 'Panqueca de frango low carb',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      '2 ovos',
      '1 colh. (sopa) de requeijão',
      'Frango desfiado',
    ],
    calories: 290,
    prepTime: '20 min',
    difficulty: 'Médio',
    protein: 32,
    carbs: 6,
    fats: 14,
    tags: ['Baixo Carboidrato', 'Proteico', 'Recheado'],
    instructions: [
      'Bata 2 ovos com 1 colh. (sopa) de requeijão.',
      'Faça panquecas finas.',
      'Recheie com frango desfiado.',
    ],
  },
  {
    id: 'almoco14',
    name: 'Lasanha de berinjela',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      'Berinjela',
      'Molho de tomate',
      'Frango',
    ],
    calories: 340,
    prepTime: '40 min',
    difficulty: 'Médio',
    protein: 28,
    carbs: 18,
    fats: 16,
    tags: ['Baixo Carboidrato', 'Assado', 'Italiano'],
    instructions: [
      'Corte berinjela em tiras e grelhe.',
      'Monte camadas com molho de tomate e frango.',
      'Asse 20–30 min.',
    ],
  },
  {
    id: 'almoco15',
    name: 'Caldo detox de legumes',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Abobrinha',
      'Cenoura',
      'Couve',
      'Temperos',
    ],
    calories: 120,
    prepTime: '20 min',
    difficulty: 'Fácil',
    protein: 4,
    carbs: 18,
    fats: 3,
    tags: ['Detox', 'Leve', 'Vegetariano'],
    instructions: [
      'Cozinhe abobrinha, cenoura e couve.',
      'Bata tudo no liquidificador.',
      'Tempere e sirva.',
    ],
  },
  {
    id: 'almoco16',
    name: 'Frango empanado na airfryer',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Filés de frango',
      'Ovo',
      'Aveia',
    ],
    calories: 320,
    prepTime: '20 min',
    difficulty: 'Fácil',
    protein: 38,
    carbs: 18,
    fats: 10,
    tags: ['Proteico', 'Crocante', 'Airfryer'],
    instructions: [
      'Passe filés de frango no ovo.',
      'Empane com aveia.',
      'Coloque na airfryer 15 min a 180°C.',
    ],
  },
  {
    id: 'almoco17',
    name: 'Tilápia crocante sem óleo',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Tilápia',
      'Aveia',
      'Temperos',
    ],
    calories: 240,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 32,
    carbs: 12,
    fats: 6,
    tags: ['Proteico', 'Crocante', 'Peixe'],
    instructions: [
      'Misture aveia + temperos.',
      'Empane a tilápia.',
      'Asse 20 min ou airfryer.',
    ],
  },
  {
    id: 'almoco18',
    name: 'Salmão com crosta de gergelim',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Salmão',
      'Gergelim',
    ],
    calories: 380,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 35,
    carbs: 4,
    fats: 24,
    tags: ['Proteico', 'Ômega 3', 'Grelhado'],
    instructions: [
      'Passe o salmão em gergelim.',
      'Grelhe 3–4 min cada lado.',
    ],
  },
  {
    id: 'almoco19',
    name: 'Purê de couve-flor low carb',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Couve-flor',
      'Sal',
      '1 colh. (chá) de manteiga light',
    ],
    calories: 80,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 3,
    carbs: 8,
    fats: 4,
    tags: ['Baixo Carboidrato', 'Leve', 'Vegetariano'],
    instructions: [
      'Cozinhe couve-flor até amolecer.',
      'Bata com sal e 1 colh. (chá) de manteiga light.',
    ],
  },
  {
    id: 'almoco20',
    name: 'Frango xadrez fit',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      'Frango em cubos',
      'Pimentões',
      'Cebola',
      'Shoyu light',
    ],
    calories: 300,
    prepTime: '20 min',
    difficulty: 'Médio',
    protein: 32,
    carbs: 15,
    fats: 10,
    tags: ['Proteico', 'Asiático', 'Colorido'],
    instructions: [
      'Refogue frango em cubos.',
      'Junte pimentões e cebola.',
      'Finalize com shoyu light.',
    ],
  },
  {
    id: 'almoco21',
    name: 'Tofu grelhado',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Tofu',
      'Shoyu',
    ],
    calories: 180,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 18,
    carbs: 6,
    fats: 10,
    tags: ['Vegetariano', 'Proteico', 'Grelhado'],
    instructions: [
      'Corte tofu em cubos.',
      'Tempere com shoyu.',
      'Grelhe até dourar.',
    ],
  },
  {
    id: 'almoco22',
    name: 'Arroz de couve-flor',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Couve-flor',
      'Azeite',
      'Alho',
    ],
    calories: 90,
    prepTime: '10 min',
    difficulty: 'Fácil',
    protein: 4,
    carbs: 10,
    fats: 4,
    tags: ['Baixo Carboidrato', 'Leve', 'Vegetariano'],
    instructions: [
      'Triture couve-flor até virar "arroz".',
      'Refogue com azeite e alho.',
    ],
  },
  {
    id: 'almoco23',
    name: 'Escondidinho de batata-doce',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      'Batata-doce',
      'Frango',
    ],
    calories: 380,
    prepTime: '35 min',
    difficulty: 'Médio',
    protein: 28,
    carbs: 42,
    fats: 10,
    tags: ['Completo', 'Assado', 'Brasileiro'],
    instructions: [
      'Faça purê de batata-doce.',
      'Recheie com frango.',
      'Asse 20 min.',
    ],
  },
  {
    id: 'almoco24',
    name: 'Sopa de abóbora',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Abóbora',
      'Temperos',
    ],
    calories: 140,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 4,
    carbs: 28,
    fats: 2,
    tags: ['Leve', 'Cremoso', 'Vegetariano'],
    instructions: [
      'Cozinhe cubos de abóbora.',
      'Bata com água do cozimento.',
      'Tempere.',
    ],
  },
  {
    id: 'almoco25',
    name: 'Salada tropical com manga',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      'Folhas verdes',
      'Manga picada',
      'Frango ou atum',
      'Azeite + limão',
    ],
    calories: 280,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 25,
    carbs: 22,
    fats: 10,
    tags: ['Tropical', 'Leve', 'Salada'],
    instructions: [
      'Misture folhas verdes, manga picada, frango ou atum.',
      'Tempere com azeite + limão.',
    ],
  },
  {
    id: 'almoco26',
    name: 'Macarrão integral com atum',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      'Macarrão integral',
      'Atum',
      'Tomate',
      'Azeite',
    ],
    calories: 380,
    prepTime: '20 min',
    difficulty: 'Fácil',
    protein: 28,
    carbs: 45,
    fats: 10,
    tags: ['Proteico', 'Integral', 'Rápido'],
    instructions: [
      'Cozinhe o macarrão.',
      'Misture atum + tomate + azeite.',
      'Sirva.',
    ],
  },
  {
    id: 'almoco27',
    name: 'Moqueca leve de peixe',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      'Pimentões',
      'Cebola',
      'Peixe',
      'Leite de coco light',
    ],
    calories: 320,
    prepTime: '25 min',
    difficulty: 'Médio',
    protein: 30,
    carbs: 12,
    fats: 16,
    tags: ['Brasileiro', 'Peixe', 'Cremoso'],
    instructions: [
      'Refogue pimentões + cebola.',
      'Coloque peixe em pedaços.',
      'Adicione leite de coco light.',
      'Cozinhe 15 min.',
    ],
  },
  {
    id: 'almoco28',
    name: 'Omelete grande recheada',
    category: 'Jantar',
    type: 'Salgado',
    ingredients: [
      '3 ovos',
      'Verduras picadas',
    ],
    calories: 260,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 22,
    carbs: 8,
    fats: 16,
    tags: ['Proteico', 'Rápido', 'Vegetariano'],
    instructions: [
      'Bata 3 ovos.',
      'Coloque verduras picadas.',
      'Cozinhe em fogo baixo.',
    ],
  },
  {
    id: 'almoco29',
    name: 'Tabule',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      'Trigo fino',
      'Tomate',
      'Pepino',
      'Hortelã',
      'Limão',
    ],
    calories: 220,
    prepTime: '20 min',
    difficulty: 'Fácil',
    protein: 6,
    carbs: 38,
    fats: 5,
    tags: ['Vegetariano', 'Mediterrâneo', 'Refrescante'],
    instructions: [
      'Hidrate trigo fino.',
      'Misture tomate, pepino, hortelã e limão.',
    ],
  },
  {
    id: 'almoco30',
    name: 'Feijão com legumes',
    category: 'Almoço',
    type: 'Salgado',
    ingredients: [
      'Feijão',
      'Legumes picados',
    ],
    calories: 280,
    prepTime: '30 min',
    difficulty: 'Fácil',
    protein: 14,
    carbs: 42,
    fats: 4,
    tags: ['Vegetariano', 'Rico em Fibras', 'Brasileiro'],
    instructions: [
      'Cozinhe feijão normalmente.',
      'Acrescente legumes picados.',
      'Ferva mais 10 min.',
    ],
  },

  // LANCHES SALGADOS - 20 RECEITAS
  {
    id: 'lanche1',
    name: 'Coxinha fit de batata-doce',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Batata-doce',
      'Frango',
    ],
    calories: 180,
    prepTime: '30 min',
    difficulty: 'Médio',
    protein: 15,
    carbs: 22,
    fats: 5,
    tags: ['Fit', 'Airfryer', 'Brasileiro'],
    instructions: [
      'Cozinhe batata-doce e amasse.',
      'Recheie com frango.',
      'Modele e leve à airfryer 15 min.',
    ],
  },
  {
    id: 'lanche2',
    name: 'Bolinho de frango airfryer',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Frango desfiado',
      'Ovo',
      'Cheiro-verde',
    ],
    calories: 160,
    prepTime: '20 min',
    difficulty: 'Fácil',
    protein: 18,
    carbs: 8,
    fats: 6,
    tags: ['Proteico', 'Airfryer', 'Rápido'],
    instructions: [
      'Misture frango desfiado + ovo + cheiro-verde.',
      'Modele bolinhos.',
      'Airfryer 12 min.',
    ],
  },
  {
    id: 'lanche3',
    name: 'Palitos de abobrinha assados',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Abobrinha',
      'Aveia',
      'Ervas',
    ],
    calories: 120,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 5,
    carbs: 18,
    fats: 4,
    tags: ['Vegetariano', 'Crocante', 'Assado'],
    instructions: [
      'Corte abobrinha em tiras.',
      'Empane com aveia e ervas.',
      'Asse 20 min.',
    ],
  },
  {
    id: 'lanche4',
    name: 'Torta de legumes',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Ovos',
      'Aveia',
      'Legumes',
    ],
    calories: 220,
    prepTime: '30 min',
    difficulty: 'Médio',
    protein: 12,
    carbs: 24,
    fats: 8,
    tags: ['Vegetariano', 'Assado', 'Completo'],
    instructions: [
      'Misture ovos + aveia + legumes.',
      'Asse 25 min.',
    ],
  },
  {
    id: 'lanche5',
    name: 'Pão de queijo fit',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Tapioca',
      'Queijo',
      'Ovo',
    ],
    calories: 180,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 10,
    carbs: 20,
    fats: 7,
    tags: ['Sem Glúten', 'Brasileiro', 'Assado'],
    instructions: [
      'Misture tapioca + queijo + ovo.',
      'Asse 20 min.',
    ],
  },
  {
    id: 'lanche6',
    name: 'Chips de batata-doce',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Batata-doce',
      'Sal',
      'Azeite',
    ],
    calories: 140,
    prepTime: '30 min',
    difficulty: 'Fácil',
    protein: 2,
    carbs: 28,
    fats: 3,
    tags: ['Vegano', 'Crocante', 'Assado'],
    instructions: [
      'Corte fininho.',
      'Asse até dourar.',
    ],
  },
  {
    id: 'lanche7',
    name: 'Bolinho de brócolis',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Brócolis',
      'Ovo',
      'Queijo',
    ],
    calories: 160,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 12,
    carbs: 10,
    fats: 8,
    tags: ['Vegetariano', 'Proteico', 'Assado'],
    instructions: [
      'Misture brócolis + ovo + queijo.',
      'Asse 20 min.',
    ],
  },
  {
    id: 'lanche8',
    name: 'Quibe de abóbora',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Abóbora cozida',
      'Trigo',
      'Temperos',
    ],
    calories: 200,
    prepTime: '35 min',
    difficulty: 'Médio',
    protein: 8,
    carbs: 32,
    fats: 5,
    tags: ['Vegetariano', 'Árabe', 'Assado'],
    instructions: [
      'Misture abóbora cozida + trigo + temperos.',
      'Asse 30 min.',
    ],
  },
  {
    id: 'lanche9',
    name: 'Empadinha de frango sem massa',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Frango',
      'Requeijão light',
    ],
    calories: 180,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 20,
    carbs: 6,
    fats: 8,
    tags: ['Sem Glúten', 'Proteico', 'Assado'],
    instructions: [
      'Misture frango + requeijão light.',
      'Coloque em forminhas.',
      'Asse 20 min.',
    ],
  },
  {
    id: 'lanche10',
    name: 'Bolinho de atum',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Atum',
      'Ovo',
      'Aveia',
    ],
    calories: 170,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 22,
    carbs: 12,
    fats: 5,
    tags: ['Proteico', 'Assado', 'Peixe'],
    instructions: [
      'Misture atum + ovo + aveia.',
      'Asse 20 min.',
    ],
  },
  {
    id: 'lanche11',
    name: 'Mini wraps light',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Folha de alface',
      'Peito de peru',
      'Cottage',
    ],
    calories: 120,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 15,
    carbs: 5,
    fats: 4,
    tags: ['Rápido', 'Proteico', 'Leve'],
    instructions: [
      'Use folha de alface + peito de peru + cottage.',
    ],
  },
  {
    id: 'lanche12',
    name: 'Ovos cozidos temperados',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Ovos',
      'Sal',
      'Pimenta',
      'Páprica',
    ],
    calories: 140,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 12,
    carbs: 2,
    fats: 10,
    tags: ['Proteico', 'Rápido', 'Simples'],
    instructions: [
      'Corte ao meio e coloque sal + pimenta + páprica.',
    ],
  },
  {
    id: 'lanche13',
    name: 'Bruschetta integral',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Pão integral',
      'Tomate',
      'Manjericão',
    ],
    calories: 160,
    prepTime: '10 min',
    difficulty: 'Fácil',
    protein: 6,
    carbs: 24,
    fats: 5,
    tags: ['Vegetariano', 'Italiano', 'Rápido'],
    instructions: [
      'Torre pão integral + tomate + manjericão.',
    ],
  },
  {
    id: 'lanche14',
    name: 'Mini pizza de berinjela',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Berinjela',
      'Molho',
      'Queijo',
    ],
    calories: 140,
    prepTime: '20 min',
    difficulty: 'Fácil',
    protein: 8,
    carbs: 12,
    fats: 7,
    tags: ['Vegetariano', 'Baixo Carboidrato', 'Assado'],
    instructions: [
      'Fatie a berinjela, cubra com molho e queijo, asse 15 min.',
    ],
  },
  {
    id: 'lanche15',
    name: 'Torta fria de ricota',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Ricota',
      'Cenoura',
      'Temperos',
      'Pão integral',
    ],
    calories: 200,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 12,
    carbs: 22,
    fats: 7,
    tags: ['Vegetariano', 'Frio', 'Leve'],
    instructions: [
      'Misture ricota + cenoura + temperos.',
      'Monte camadas no pão integral.',
    ],
  },
  {
    id: 'lanche16',
    name: 'Pastel de forno integral',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Massa integral',
      'Frango',
    ],
    calories: 220,
    prepTime: '30 min',
    difficulty: 'Médio',
    protein: 15,
    carbs: 28,
    fats: 6,
    tags: ['Integral', 'Assado', 'Brasileiro'],
    instructions: [
      'Recheie massa integral com frango e asse.',
    ],
  },
  {
    id: 'lanche17',
    name: 'Bolinho de couve-flor',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Couve-flor',
      'Ovo',
      'Temperos',
    ],
    calories: 130,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 8,
    carbs: 12,
    fats: 6,
    tags: ['Vegetariano', 'Baixo Carboidrato', 'Assado'],
    instructions: [
      'Misture couve-flor + ovo + temperos.',
      'Asse até dourar.',
    ],
  },
  {
    id: 'lanche18',
    name: 'Nuggets caseiros',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Frango triturado',
      'Aveia',
      'Temperos',
    ],
    calories: 200,
    prepTime: '20 min',
    difficulty: 'Fácil',
    protein: 24,
    carbs: 15,
    fats: 6,
    tags: ['Proteico', 'Airfryer', 'Infantil'],
    instructions: [
      'Frango triturado + aveia + temperos.',
      'Airfryer 15 min.',
    ],
  },
  {
    id: 'lanche19',
    name: 'Pão integral recheado light',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Pão integral',
      'Cottage',
      'Tomate',
      'Sal',
    ],
    calories: 180,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 12,
    carbs: 26,
    fats: 4,
    tags: ['Rápido', 'Leve', 'Simples'],
    instructions: [
      'Coloque cottage + tomate + sal.',
    ],
  },
  {
    id: 'lanche20',
    name: 'Mini sanduíche de cottage',
    category: 'Lanche',
    type: 'Salgado',
    ingredients: [
      'Pão integral',
      'Cottage',
      'Peito de peru',
    ],
    calories: 190,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 16,
    carbs: 24,
    fats: 4,
    tags: ['Rápido', 'Proteico', 'Simples'],
    instructions: [
      'Pão integral + cottage + peito de peru.',
    ],
  },

  // LANCHES DOCES - 15 RECEITAS
  {
    id: 'doce1',
    name: 'Gelatina natural com frutas',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Gelatina sem açúcar',
      'Frutas picadas',
    ],
    calories: 80,
    prepTime: '10 min + geladeira',
    difficulty: 'Fácil',
    protein: 4,
    carbs: 15,
    fats: 0,
    tags: ['Leve', 'Refrescante', 'Sem Açúcar'],
    instructions: [
      'Prepare gelatina sem açúcar e adicione frutas picadas.',
    ],
  },
  {
    id: 'doce2',
    name: 'Mousse fit de maracujá',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Iogurte',
      'Maracujá',
      'Gelatina sem sabor',
    ],
    calories: 120,
    prepTime: '15 min + geladeira',
    difficulty: 'Fácil',
    protein: 8,
    carbs: 18,
    fats: 2,
    tags: ['Cremoso', 'Refrescante', 'Proteico'],
    instructions: [
      'Iogurte + maracujá + gelatina sem sabor.',
    ],
  },
  {
    id: 'doce3',
    name: 'Bolo de chocolate low carb',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Ovo',
      'Cacau',
      'Aveia',
      'Adoçante',
    ],
    calories: 160,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 8,
    carbs: 18,
    fats: 6,
    tags: ['Baixo Carboidrato', 'Chocolate', 'Assado'],
    instructions: [
      'Ovo + cacau + aveia + adoçante.',
      'Asse 15–20 min.',
    ],
  },
  {
    id: 'doce4',
    name: 'Pudim sem açúcar',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Leite desnatado',
      'Ovos',
      'Adoçante',
    ],
    calories: 140,
    prepTime: '50 min',
    difficulty: 'Médio',
    protein: 10,
    carbs: 15,
    fats: 4,
    tags: ['Cremoso', 'Sem Açúcar', 'Brasileiro'],
    instructions: [
      'Bata leite desnatado + ovos + adoçante.',
      'Banho-maria 40 min.',
    ],
  },
  {
    id: 'doce5',
    name: 'Banana assada com canela',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Banana',
      'Canela',
    ],
    calories: 120,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 2,
    carbs: 28,
    fats: 0,
    tags: ['Simples', 'Sem Açúcar', 'Assado'],
    instructions: [
      'Corte e leve ao forno 10 min.',
    ],
  },
  {
    id: 'doce6',
    name: 'Bombom de uva fit',
    category: 'Lanche',
    type: 'Doce',
    ingredients: [
      'Uva',
      'Pasta de cacau',
    ],
    calories: 100,
    prepTime: '10 min + freezer',
    difficulty: 'Fácil',
    protein: 2,
    carbs: 20,
    fats: 2,
    tags: ['Refrescante', 'Chocolate', 'Congelado'],
    instructions: [
      'Uva + pasta de cacau + congelar.',
    ],
  },
  {
    id: 'doce7',
    name: 'Trufa proteica',
    category: 'Lanche',
    type: 'Doce',
    ingredients: [
      'Whey',
      'Cacau',
      'Pasta de amendoim',
    ],
    calories: 140,
    prepTime: '15 min',
    difficulty: 'Fácil',
    protein: 12,
    carbs: 10,
    fats: 7,
    tags: ['Proteico', 'Chocolate', 'Energético'],
    instructions: [
      'Whey + cacau + pasta de amendoim.',
    ],
  },
  {
    id: 'doce8',
    name: 'Brownie fit',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Cacau',
      'Aveia',
      'Banana',
    ],
    calories: 150,
    prepTime: '25 min',
    difficulty: 'Fácil',
    protein: 5,
    carbs: 24,
    fats: 4,
    tags: ['Chocolate', 'Sem Açúcar Refinado', 'Assado'],
    instructions: [
      'Cacau + aveia + banana.',
      'Asse 20 min.',
    ],
  },
  {
    id: 'doce9',
    name: 'Biscoito de aveia',
    category: 'Lanche',
    type: 'Doce',
    ingredients: [
      'Aveia',
      'Banana',
      'Cacau',
    ],
    calories: 130,
    prepTime: '20 min',
    difficulty: 'Fácil',
    protein: 4,
    carbs: 22,
    fats: 3,
    tags: ['Crocante', 'Sem Açúcar Refinado', 'Assado'],
    instructions: [
      'Aveia + banana + cacau.',
      'Asse 15 min.',
    ],
  },
  {
    id: 'doce10',
    name: 'Torta light de maçã',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Maçã',
      'Aveia',
      'Canela',
    ],
    calories: 180,
    prepTime: '30 min',
    difficulty: 'Médio',
    protein: 5,
    carbs: 32,
    fats: 4,
    tags: ['Assado', 'Sem Açúcar Refinado', 'Frutas'],
    instructions: [
      'Maçã + aveia + canela.',
      'Asse 25 min.',
    ],
  },
  {
    id: 'doce11',
    name: 'Sorbet de frutas',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Frutas congeladas',
    ],
    calories: 90,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 1,
    carbs: 22,
    fats: 0,
    tags: ['Refrescante', 'Vegano', 'Sem Açúcar'],
    instructions: [
      'Congele fruta e bata no processador.',
    ],
  },
  {
    id: 'doce12',
    name: 'Geladinho proteico',
    category: 'Lanche',
    type: 'Doce',
    ingredients: [
      'Whey',
      'Água',
      'Fruta',
    ],
    calories: 100,
    prepTime: '5 min + freezer',
    difficulty: 'Fácil',
    protein: 15,
    carbs: 10,
    fats: 1,
    tags: ['Proteico', 'Refrescante', 'Congelado'],
    instructions: [
      'Whey + água + fruta.',
    ],
  },
  {
    id: 'doce13',
    name: 'Creme de cacau com banana congelada',
    category: 'Sobremesa',
    type: 'Doce',
    ingredients: [
      'Banana congelada',
      'Cacau',
    ],
    calories: 130,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 3,
    carbs: 28,
    fats: 2,
    tags: ['Cremoso', 'Chocolate', 'Sem Açúcar'],
    instructions: [
      'Bata banana congelada + cacau.',
    ],
  },
  {
    id: 'doce14',
    name: 'Panqueca doce',
    category: 'Lanche',
    type: 'Doce',
    ingredients: [
      'Banana',
      'Ovo',
      'Cacau',
    ],
    calories: 160,
    prepTime: '10 min',
    difficulty: 'Fácil',
    protein: 8,
    carbs: 22,
    fats: 5,
    tags: ['Proteico', 'Sem Açúcar Refinado', 'Rápido'],
    instructions: [
      'Banana + ovo + cacau.',
    ],
  },
  {
    id: 'doce15',
    name: 'Iogurte gelado com mel',
    category: 'Lanche',
    type: 'Doce',
    ingredients: [
      'Iogurte',
      '1 colher de mel',
    ],
    calories: 120,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 8,
    carbs: 18,
    fats: 2,
    tags: ['Refrescante', 'Proteico', 'Simples'],
    instructions: [
      'Iogurte + 1 colher de mel.',
    ],
  },

  // BEBIDAS E SMOOTHIES - 15 RECEITAS
  {
    id: 'bebida1',
    name: 'Suco detox verde',
    category: 'Bebida',
    type: 'Salgado',
    ingredients: [
      'Couve',
      'Limão',
      'Água',
      'Gengibre',
    ],
    calories: 40,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 2,
    carbs: 8,
    fats: 0,
    tags: ['Detox', 'Refrescante', 'Vegano'],
    instructions: [
      'Couve + limão + água + gengibre.',
    ],
  },
  {
    id: 'bebida2',
    name: 'Smoothie de frutas vermelhas',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Morango',
      'Amora',
      'Iogurte',
      'Água',
    ],
    calories: 140,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 6,
    carbs: 26,
    fats: 2,
    tags: ['Antioxidante', 'Cremoso', 'Proteico'],
    instructions: [
      'Morango + amora + iogurte + água.',
    ],
  },
  {
    id: 'bebida3',
    name: 'Limonada com chia',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Limão',
      'Água',
      'Chia hidratada',
    ],
    calories: 60,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 2,
    carbs: 12,
    fats: 2,
    tags: ['Refrescante', 'Rico em Fibras', 'Detox'],
    instructions: [
      'Limão + água + chia hidratada.',
    ],
  },
  {
    id: 'bebida4',
    name: 'Água saborizada',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Água',
      'Laranja',
      'Hortelã',
    ],
    calories: 20,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 0,
    carbs: 5,
    fats: 0,
    tags: ['Refrescante', 'Sem Açúcar', 'Hidratante'],
    instructions: [
      'Água + laranja + hortelã.',
    ],
  },
  {
    id: 'bebida5',
    name: 'Chá gelado termogênico',
    category: 'Bebida',
    type: 'Salgado',
    ingredients: [
      'Chá verde',
      'Gelo',
      'Limão',
    ],
    calories: 10,
    prepTime: '10 min',
    difficulty: 'Fácil',
    protein: 0,
    carbs: 2,
    fats: 0,
    tags: ['Termogênico', 'Refrescante', 'Detox'],
    instructions: [
      'Chá verde + gelo + limão.',
    ],
  },
  {
    id: 'bebida6',
    name: 'Suco de abacaxi com hortelã',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Abacaxi',
      'Hortelã',
      'Água',
    ],
    calories: 80,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 1,
    carbs: 20,
    fats: 0,
    tags: ['Refrescante', 'Tropical', 'Digestivo'],
    instructions: [
      'Bata abacaxi + hortelã + água.',
    ],
  },
  {
    id: 'bebida7',
    name: 'Shake proteico',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Whey',
      'Leite vegetal',
      'Banana',
    ],
    calories: 180,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 20,
    carbs: 22,
    fats: 3,
    tags: ['Proteico', 'Energético', 'Pós-treino'],
    instructions: [
      'Whey + leite vegetal + banana.',
    ],
  },
  {
    id: 'bebida8',
    name: 'Suco de melancia detox',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Melancia',
      'Gengibre',
      'Água',
    ],
    calories: 60,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 1,
    carbs: 14,
    fats: 0,
    tags: ['Hidratante', 'Refrescante', 'Detox'],
    instructions: [
      'Melancia + gengibre + água.',
    ],
  },
  {
    id: 'bebida9',
    name: 'Smoothie tropical',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Manga',
      'Leite de coco',
      'Gelo',
    ],
    calories: 160,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 2,
    carbs: 32,
    fats: 4,
    tags: ['Tropical', 'Cremoso', 'Refrescante'],
    instructions: [
      'Manga + leite de coco + gelo.',
    ],
  },
  {
    id: 'bebida10',
    name: 'Água com gengibre',
    category: 'Bebida',
    type: 'Salgado',
    ingredients: [
      'Água',
      'Gengibre',
    ],
    calories: 5,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 0,
    carbs: 1,
    fats: 0,
    tags: ['Detox', 'Termogênico', 'Digestivo'],
    instructions: [
      'Coloque fatias de gengibre na água.',
    ],
  },
  {
    id: 'bebida11',
    name: 'Suco antioxidante',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Açaí sem açúcar',
      'Morango',
      'Água',
    ],
    calories: 120,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 2,
    carbs: 28,
    fats: 2,
    tags: ['Antioxidante', 'Energético', 'Brasileiro'],
    instructions: [
      'Açaí sem açúcar + morango + água.',
    ],
  },
  {
    id: 'bebida12',
    name: 'Café proteico gelado',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Café',
      'Whey',
      'Gelo',
    ],
    calories: 100,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 15,
    carbs: 8,
    fats: 1,
    tags: ['Proteico', 'Energético', 'Refrescante'],
    instructions: [
      'Café + whey + gelo.',
    ],
  },
  {
    id: 'bebida13',
    name: 'Chocolate quente fit',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Cacau',
      'Leite desnatado',
      'Adoçante',
    ],
    calories: 120,
    prepTime: '10 min',
    difficulty: 'Fácil',
    protein: 8,
    carbs: 16,
    fats: 3,
    tags: ['Reconfortante', 'Chocolate', 'Sem Açúcar'],
    instructions: [
      'Cacau + leite desnatado + adoçante.',
    ],
  },
  {
    id: 'bebida14',
    name: 'Chá calmante noturno',
    category: 'Bebida',
    type: 'Salgado',
    ingredients: [
      'Camomila',
      'Mel (opcional)',
    ],
    calories: 20,
    prepTime: '10 min',
    difficulty: 'Fácil',
    protein: 0,
    carbs: 5,
    fats: 0,
    tags: ['Relaxante', 'Natural', 'Noturno'],
    instructions: [
      'Camomila + mel (opcional).',
    ],
  },
  {
    id: 'bebida15',
    name: 'Limonada suíça light',
    category: 'Bebida',
    type: 'Doce',
    ingredients: [
      'Limão',
      'Água gelada',
      'Adoçante',
    ],
    calories: 30,
    prepTime: '5 min',
    difficulty: 'Fácil',
    protein: 0,
    carbs: 8,
    fats: 0,
    tags: ['Refrescante', 'Sem Açúcar', 'Clássico'],
    instructions: [
      'Limão + água gelada + adoçante.',
    ],
  },
];

// Função para buscar receitas por categoria
export function getRecipesByCategory(category: Recipe['category']): Recipe[] {
  return recipesDatabase.filter(recipe => recipe.category === category);
}

// Função para buscar receitas por tipo
export function getRecipesByType(type: Recipe['type']): Recipe[] {
  return recipesDatabase.filter(recipe => recipe.type === type);
}

// Função para buscar receitas por tags
export function getRecipesByTag(tag: string): Recipe[] {
  return recipesDatabase.filter(recipe => recipe.tags.includes(tag));
}

// Função para buscar receitas por dificuldade
export function getRecipesByDifficulty(difficulty: Recipe['difficulty']): Recipe[] {
  return recipesDatabase.filter(recipe => recipe.difficulty === difficulty);
}

// Função para buscar receitas por calorias máximas
export function getRecipesByMaxCalories(maxCalories: number): Recipe[] {
  return recipesDatabase.filter(recipe => recipe.calories <= maxCalories);
}

// Função para buscar receita por ID
export function getRecipeById(id: string): Recipe | undefined {
  return recipesDatabase.find(recipe => recipe.id === id);
}

// Todas as tags disponíveis
export const availableTags = [
  'Proteico',
  'Baixo Carboidrato',
  'Vegetariano',
  'Vegano',
  'Sem Glúten',
  'Sem Açúcar Refinado',
  'Rápido',
  'Energético',
  'Rico em Fibras',
  'Antioxidante',
  'Brasileiro',
  'Mediterrâneo',
  'Mexicano',
  'Italiano',
  'Cremoso',
  'Crocante',
  'Assado',
  'Gourmet',
  'Reconfortante',
  'Leve',
  'Nutritivo',
  'Completo',
  'Colorido',
  'Ômega 3',
  'Probiótico',
  'Tropical',
  'Sem Farinha',
  'Fit',
  'Grelhado',
  'Recheado',
  'Integral',
  'Salada',
  'Peixe',
  'Airfryer',
  'Asiático',
  'Árabe',
  'Simples',
  'Frio',
  'Infantil',
  'Refrescante',
  'Chocolate',
  'Congelado',
  'Frutas',
  'Detox',
  'Hidratante',
  'Termogênico',
  'Digestivo',
  'Pós-treino',
  'Relaxante',
  'Natural',
  'Noturno',
  'Clássico',
];
